### ISSUE TITLE
Hackily prototype Traits and Mutation gameplay - 9 hours

### ISSUE THREAD

**Issue by hellochar** [hellochar/mito#32]
It's not proven that the proposed system of traits and mutation is actually fun. So, build a hacky prototype that implements traits and mutation (probably along with seasons and multiple fruit) so we can actually decide if it's fun, and tweak, before committing to the architecture.

- [x] Hook up existing traits (#18) to existing Cell subclass structure - 2 hours
- [x] Hackily implement multiple fruits + DNA (#14) - 2 hours
- [x] Hackily implement seasons (#8) and make games only take ~15 minutes or so - 1 hour; just make it a 15 minute game with a global timer on top
- [x] Hackily implement mutation system UI (#21) so we can get the feel of improving - 4 hours

**Comment by hellochar** [comment]
We're close here. We have:
* Per species traits
* Multiple fruits 
* A time limited game
* The ability to create descendant species based off mutations and MP

We're missing
* Epochs and mature fruit providing MP
* Design and restrictions on how descendant species and overworld expansion work together 
* Remaining 5 traits
* seasons with differentiation

**Comment by hellochar** [comment]
Prototype taught us two things: epoch turns and overworld expansion wasn't fun, and traits weren't fun or obvious. Based off this info I'm going to rethink how to move forward and do a better iteration of traits, genes, and progression in general
