### ISSUE TITLE
Milestone 1 Performance pass

### ISSUE THREAD

**Issue by hellochar** [hellochar/mito#49]
Various ways to improve performance:

## Three.js:
- [x] Batch TileRenderer with a custom shader for all tiles (load the entire spritesheet in!) - 10 hours, expect improvement: _large_
- [x] Maybe combine meshes?
- [x] Take a look at instancing
* Reduce usage of new; object pooling. expected improvement: _medium_

## Game logic:
1. Double-buffer (ping pong) game states to implement a proper update. 
1. Look at matrix multiplication. Why? Because, the way we're doing game logic right now is:
   ```
   For each entity (all tiles):
       call "step" on it
   ```
We're doing an actor based implementation for a lot of logic, when a world sweep method might be more appropriate.

### Actor based vs "world sweep"
So, for every piece of game state, we have two high level ways to implement it:
1. per-Tile step. Each tile implements stepping for itself. This is easy to code and think about, since you just put yourself in the perspective of the Tile. Also all code related to a Tile is colocated together in the Tile subclass. Also you can override update steps with subclasses.
2. The World computes that property for all Tiles. Sunlight is implemented this way since it leads to faster performance. 

So perf is the sum of all steps. But what actually happens in each step? `Tile.step(dt)` does the following: 
1. stepDarkness
2. stepDiffusion
3. stepTemperature
4. stepGravity

Lets look at each individually:
### stepDarkness

This is basically a live updating Floodfill/Djikstra's algorithm. But actually what we want is, for each tile, what is the min "light distance" from any light "sources": the air, or the Cells. The darkness computation is a pure function of:
1. world height (never changes)
2. tile position (never changes)
3. Neighbors' darkness (only changes when the neighbor changes)
4. Whether the neighbor is a Cell or not

So one could optimize this by only **computing darkness when a Cell is placed**. Actually yeah - so when a Cell is placed, you do the darkness floodfill update right there. You stop on any tiles where your contribution didn't update the tile. Boom. Easy and performant.

### stepDiffusion

So, first, the terminology is wrong. This is actually "pull" water from neighbors. What we do is:

```
for each neighbor:
  must canDiffuse(neighbor)
  if this can diffuse water:
    if neighbor has more water
      maybe pull some water from neighbor
```

This is inefficient in the following ways:
1. half of the neighbor pairs are checked twice! Because we do a checkered step but the neighbors are all eight, the diagonal neighbors are checked twice, when one check will be always false. 
2. canDiffuse only changes when tileNeighbors changes; we should cache that
3. we should do the "can diffuse water" at the very start
4. diffusion is a function of:
  * random time process
  * neighbor tile types
  * neighbor inventories
  this is likely to change every step.

### stepTemperature
We basically compute and cache `world.getCurrentTemperature()` every step. This computes this.season, this.sunAmount, and does a linear map. **We should cache getCurrentTemperature**. We can also remove stepTemperature and make `this.temperatureFloat` a getter on Tile (maybe).

### stepGravity
Honestly this one's pretty much optimized

## React UI perf
probably not too big a deal, profiling said it's fine so far

**Comment by hellochar** [comment]
5 seconds of profiling in production on:
MacBookPro 2017
Processor: 2.9 GHz i7
Memory: 16 GB 2133 MHz LPDDR3
Graphics: Radeon Pro 560 4096 MB, Intel HD Graphics 630 1536 MB

Top usages:

1. threejs `projectObject`
2. threejs `updateMatrixWorld`
3. TileRenderer `value` (I think this is updating the color) 
4. Composite Layers (oof)
5. threejs multiplyMatrices

Almost all of this is rendering related
